// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoccerBlast.Api.Data;

#nullable disable

namespace SoccerBlast.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226040427_FixSearchAliasesIdIdentity")]
    partial class FixSearchAliasesIdIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoccerBlast.Api.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeUrl")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.CompetitionExternalMap", b =>
                {
                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompetitionId", "Provider");

                    b.HasIndex("ExternalId");

                    b.HasIndex("LastSyncedUtc");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("CompetitionExternalMaps");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.Honour", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("HonourUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TrophyImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("TypeGuess")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Honours");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.HonourWinner", b =>
                {
                    b.Property<int>("HonourId")
                        .HasColumnType("integer");

                    b.Property<string>("YearLabel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TeamBadgeUrl")
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.HasKey("HonourId", "YearLabel");

                    b.HasIndex("TeamId");

                    b.ToTable("HonourWinners");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.LeagueHonourMap", b =>
                {
                    b.Property<string>("LeagueId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("HonourId")
                        .HasColumnType("integer");

                    b.HasKey("LeagueId", "HonourId");

                    b.HasIndex("HonourId");

                    b.HasIndex("LeagueId");

                    b.ToTable("LeagueHonourMaps");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.LeagueSeasonStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Draw")
                        .HasColumnType("integer");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Loss")
                        .HasColumnType("integer");

                    b.Property<int>("Played")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScrapedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("StrDescription")
                        .HasColumnType("text");

                    b.Property<string>("TeamBadgeUrl")
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Win")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Season");

                    b.HasIndex("LeagueId", "Season", "TeamId")
                        .IsUnique();

                    b.ToTable("LeagueSeasonStandings");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UtcDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UtcDate");

                    b.HasIndex("AwayTeamId", "UtcDate");

                    b.HasIndex("CompetitionId", "UtcDate");

                    b.HasIndex("HomeTeamId", "UtcDate");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.MatchDaySyncState", b =>
                {
                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int?>("LastSyncedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("LocalDate");

                    b.ToTable("MatchDaySyncStates");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc");

                    b.HasIndex("UrlHash")
                        .IsUnique();

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.NewsItemTeam", b =>
                {
                    b.Property<int>("NewsItemId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("NewsItemId", "TeamId");

                    b.HasIndex("NewsItemId");

                    b.HasIndex("TeamId");

                    b.ToTable("NewsItemTeams");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.PlayerExternalMap", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId", "Provider");

                    b.HasIndex("ExternalId");

                    b.HasIndex("LastSyncedUtc");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("PlayerExternalMaps");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.SearchAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AliasNorm")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<int>("HitCount")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HitCount");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("Type", "AliasNorm");

                    b.HasIndex("Type", "Canonical", "Alias")
                        .IsUnique();

                    b.ToTable("SearchAliases");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SyncedMatches")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SyncType", "LocalDate", "Success", "FinishedAtUtc");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CrestUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SportsDbId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SportsDbId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.TeamHonour", b =>
                {
                    b.Property<string>("TeamId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("HonourId")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "HonourId");

                    b.HasIndex("HonourId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamHonours");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.TeamProfile", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("BadgeUrl")
                        .HasColumnType("text");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("Facebook")
                        .HasColumnType("text");

                    b.Property<int?>("FormedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("JerseyUrl")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Leagues")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("text");

                    b.Property<int?>("StadiumCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("StadiumLocation")
                        .HasColumnType("text");

                    b.Property<string>("StadiumName")
                        .HasColumnType("text");

                    b.Property<string>("TertiaryColor")
                        .HasColumnType("text");

                    b.Property<string>("Twitter")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<string>("Youtube")
                        .HasColumnType("text");

                    b.HasKey("TeamId");

                    b.HasIndex("LastUpdatedUtc");

                    b.ToTable("TeamProfiles");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.VenueExternalMap", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VenueId", "Provider");

                    b.HasIndex("ExternalId");

                    b.HasIndex("LastSyncedUtc");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("VenueExternalMaps");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.CompetitionExternalMap", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.HonourWinner", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Honour", "Honour")
                        .WithMany("HonourWinners")
                        .HasForeignKey("HonourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Honour");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.LeagueHonourMap", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Honour", "Honour")
                        .WithMany()
                        .HasForeignKey("HonourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Honour");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.Match", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerBlast.Api.Models.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerBlast.Api.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.NewsItemTeam", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.NewsItem", "NewsItem")
                        .WithMany()
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerBlast.Api.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.Player", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamId");

                    b.Navigation("CurrentTeam");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.PlayerExternalMap", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.TeamHonour", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Honour", "Honour")
                        .WithMany("TeamHonours")
                        .HasForeignKey("HonourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Honour");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.TeamProfile", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Team", "Team")
                        .WithOne()
                        .HasForeignKey("SoccerBlast.Api.Models.TeamProfile", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.VenueExternalMap", b =>
                {
                    b.HasOne("SoccerBlast.Api.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SoccerBlast.Api.Models.Honour", b =>
                {
                    b.Navigation("HonourWinners");

                    b.Navigation("TeamHonours");
                });
#pragma warning restore 612, 618
        }
    }
}
