using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SoccerBlast.Api.Migrations
{
    /// <inheritdoc />
    public partial class FixSearchAliasesIdColumn : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // PostgreSQL: ensure SearchAliases.Id has a default so INSERT without Id works.
            // Idempotent: no-op if column already has identity/serial.
            migrationBuilder.Sql(@"
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON a.attrelid = c.oid
    JOIN pg_namespace n ON c.relnamespace = n.oid
    WHERE n.nspname = 'public' AND c.relname = 'SearchAliases'
    AND a.attname = 'Id' AND a.attidentity IN ('d','a')
  ) THEN
    ALTER TABLE ""SearchAliases"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;
");
            migrationBuilder.Sql(@"
SELECT setval(
  pg_get_serial_sequence('""SearchAliases""', 'Id'),
  GREATEST(COALESCE((SELECT MAX(""Id"") FROM ""SearchAliases""), 0) + 1, 1)
);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DO $$
BEGIN
  ALTER TABLE ""SearchAliases"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;
");
        }
    }
}
